/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Provides information about the scan status of a discovered resource.
type DiscoveryDiscoveredDetails struct {
	// Output only. An operation that indicates the status of the current scan.
	Operation *LongrunningOperation `json:"operation,omitempty"`
}
