/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// An artifact that can be deployed in some runtime.
type ApiDeployable struct {
	// Resource URI for the artifact being deployed.
	ResourceUri []string `json:"resource_uri,omitempty"`
}
