/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type CvssAuthentication string

// List of CVSSAuthentication
const (
	UNSPECIFIED_CvssAuthentication CvssAuthentication = "AUTHENTICATION_UNSPECIFIED"
	MULTIPLE_CvssAuthentication CvssAuthentication = "AUTHENTICATION_MULTIPLE"
	SINGLE_CvssAuthentication CvssAuthentication = "AUTHENTICATION_SINGLE"
	NONE_CvssAuthentication CvssAuthentication = "AUTHENTICATION_NONE"
)
