/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas
// HashHashType : Specifies the hash algorithm.   - HASH_TYPE_UNSPECIFIED: Unknown.  - SHA256: A SHA-256 hash.
type HashHashType string

// List of HashHashType
const (
	HASH_TYPE_UNSPECIFIED_HashHashType HashHashType = "HASH_TYPE_UNSPECIFIED"
	SHA256_HashHashType HashHashType = "SHA256"
)
