/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Defines a hash object for use in Materials and Products.
type LinkArtifactHashes struct {
	Sha256 string `json:"sha256,omitempty"`
}
