/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type CvssAttackComplexity string

// List of CVSSAttackComplexity
const (
	UNSPECIFIED_CvssAttackComplexity CvssAttackComplexity = "ATTACK_COMPLEXITY_UNSPECIFIED"
	LOW_CvssAttackComplexity CvssAttackComplexity = "ATTACK_COMPLEXITY_LOW"
	HIGH_CvssAttackComplexity CvssAttackComplexity = "ATTACK_COMPLEXITY_HIGH"
)
