/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Response for creating occurrences in batch.
type V1beta1BatchCreateOccurrencesResponse struct {
	// The occurrences that were created.
	Occurrences []V1beta1Occurrence `json:"occurrences,omitempty"`
}
