/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas
// LayerDirective : Instructions from Dockerfile.   - DIRECTIVE_UNSPECIFIED: Default value for unsupported/missing directive.  - MAINTAINER: https://docs.docker.com/engine/reference/builder/  - RUN: https://docs.docker.com/engine/reference/builder/  - CMD: https://docs.docker.com/engine/reference/builder/  - LABEL: https://docs.docker.com/engine/reference/builder/  - EXPOSE: https://docs.docker.com/engine/reference/builder/  - ENV: https://docs.docker.com/engine/reference/builder/  - ADD: https://docs.docker.com/engine/reference/builder/  - COPY: https://docs.docker.com/engine/reference/builder/  - ENTRYPOINT: https://docs.docker.com/engine/reference/builder/  - VOLUME: https://docs.docker.com/engine/reference/builder/  - USER: https://docs.docker.com/engine/reference/builder/  - WORKDIR: https://docs.docker.com/engine/reference/builder/  - ARG: https://docs.docker.com/engine/reference/builder/  - ONBUILD: https://docs.docker.com/engine/reference/builder/  - STOPSIGNAL: https://docs.docker.com/engine/reference/builder/  - HEALTHCHECK: https://docs.docker.com/engine/reference/builder/  - SHELL: https://docs.docker.com/engine/reference/builder/
type LayerDirective string

// List of LayerDirective
const (
	DIRECTIVE_UNSPECIFIED_LayerDirective LayerDirective = "DIRECTIVE_UNSPECIFIED"
	MAINTAINER_LayerDirective LayerDirective = "MAINTAINER"
	RUN_LayerDirective LayerDirective = "RUN"
	CMD_LayerDirective LayerDirective = "CMD"
	LABEL_LayerDirective LayerDirective = "LABEL"
	EXPOSE_LayerDirective LayerDirective = "EXPOSE"
	ENV_LayerDirective LayerDirective = "ENV"
	ADD_LayerDirective LayerDirective = "ADD"
	COPY_LayerDirective LayerDirective = "COPY"
	ENTRYPOINT_LayerDirective LayerDirective = "ENTRYPOINT"
	VOLUME_LayerDirective LayerDirective = "VOLUME"
	USER_LayerDirective LayerDirective = "USER"
	WORKDIR_LayerDirective LayerDirective = "WORKDIR"
	ARG_LayerDirective LayerDirective = "ARG"
	ONBUILD_LayerDirective LayerDirective = "ONBUILD"
	STOPSIGNAL_LayerDirective LayerDirective = "STOPSIGNAL"
	HEALTHCHECK_LayerDirective LayerDirective = "HEALTHCHECK"
	SHELL_LayerDirective LayerDirective = "SHELL"
)
