/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type CvssAttackVector string

// List of CVSSAttackVector
const (
	UNSPECIFIED_CvssAttackVector CvssAttackVector = "ATTACK_VECTOR_UNSPECIFIED"
	NETWORK_CvssAttackVector CvssAttackVector = "ATTACK_VECTOR_NETWORK"
	ADJACENT_CvssAttackVector CvssAttackVector = "ATTACK_VECTOR_ADJACENT"
	LOCAL_CvssAttackVector CvssAttackVector = "ATTACK_VECTOR_LOCAL"
	PHYSICAL_CvssAttackVector CvssAttackVector = "ATTACK_VECTOR_PHYSICAL"
)
