/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type SpdxLicense struct {
	Expression string `json:"expression,omitempty"`
	Comments string `json:"comments,omitempty"`
}
