/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// This defines the format used to record keys used in the software supply chain. An in-toto link is attested using one or more keys defined in the in-toto layout. An example of this is: {   \"key_id\": \"776a00e29f3559e0141b3b096f696abc6cfb0c657ab40f441132b345b0...\",   \"key_type\": \"rsa\",   \"public_key_value\": \"-----BEGIN PUBLIC KEY-----\\nMIIBojANBgkqhkiG9w0B...\",   \"key_scheme\": \"rsassa-pss-sha256\" } The format for in-toto's key definition can be found in section 4.2 of the in-toto specification.
type IntotoSigningKey struct {
	// key_id is an identifier for the signing key.
	KeyId string `json:"keyId,omitempty"`
	// This field identifies the specific signing method. Eg: \"rsa\", \"ed25519\", and \"ecdsa\".
	KeyType string `json:"keyType,omitempty"`
	// This field contains the actual public key.
	PublicKeyValue string `json:"publicKeyValue,omitempty"`
	// This field contains the corresponding signature scheme. Eg: \"rsassa-pss-sha256\".
	KeyScheme string `json:"keyScheme,omitempty"`
}
