/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// This corresponds to a signed in-toto link - it is made up of one or more signatures and the in-toto link itself. This is used for occurrences of a Grafeas in-toto note.
type V1beta1intotoDetails struct {
	Signatures []V1beta1intotoSignature `json:"signatures,omitempty"`
	Signed *IntotoLink `json:"signed,omitempty"`
}
