/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas
// FileNoteFileType : - FILE_TYPE_UNSPECIFIED: Unspecified  - SOURCE: The file is human readable source code (.c, .html, etc.)  - BINARY: The file is a compiled object, target image or binary executable (.o, .a, etc.)  - ARCHIVE: The file represents an archive (.tar, .jar, etc.)  - APPLICATION: The file is associated with a specific application type (MIME type of application/_*)  - AUDIO: The file is associated with an audio file (MIME type of audio/_* , e.g. .mp3)  - IMAGE: The file is associated with an picture image file (MIME type of image/_*, e.g., .jpg, .gif)  - TEXT: The file is human readable text file (MIME type of text/_*)  - VIDEO: The file is associated with a video file type (MIME type of video/_*)  - DOCUMENTATION: The file serves as documentation  - SPDX: The file is an SPDX document  - OTHER: The file doesn't fit into the above categories (generated artifacts, data files, etc.)
type FileNoteFileType string

// List of FileNoteFileType
const (
	FILE_TYPE_UNSPECIFIED_FileNoteFileType FileNoteFileType = "FILE_TYPE_UNSPECIFIED"
	SOURCE_FileNoteFileType FileNoteFileType = "SOURCE"
	BINARY_FileNoteFileType FileNoteFileType = "BINARY"
	ARCHIVE_FileNoteFileType FileNoteFileType = "ARCHIVE"
	APPLICATION_FileNoteFileType FileNoteFileType = "APPLICATION"
	AUDIO_FileNoteFileType FileNoteFileType = "AUDIO"
	IMAGE_FileNoteFileType FileNoteFileType = "IMAGE"
	TEXT_FileNoteFileType FileNoteFileType = "TEXT"
	VIDEO_FileNoteFileType FileNoteFileType = "VIDEO"
	DOCUMENTATION_FileNoteFileType FileNoteFileType = "DOCUMENTATION"
	SPDX_FileNoteFileType FileNoteFileType = "SPDX"
	OTHER_FileNoteFileType FileNoteFileType = "OTHER"
)
