/*
 * proto/v1beta1/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type CvsSv3PrivilegesRequired string

// List of CVSSv3PrivilegesRequired
const (
	UNSPECIFIED_CvsSv3PrivilegesRequired CvsSv3PrivilegesRequired = "PRIVILEGES_REQUIRED_UNSPECIFIED"
	NONE_CvsSv3PrivilegesRequired CvsSv3PrivilegesRequired = "PRIVILEGES_REQUIRED_NONE"
	LOW_CvsSv3PrivilegesRequired CvsSv3PrivilegesRequired = "PRIVILEGES_REQUIRED_LOW"
	HIGH_CvsSv3PrivilegesRequired CvsSv3PrivilegesRequired = "PRIVILEGES_REQUIRED_HIGH"
)
