/*
 * proto/v1beta1/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// An entity that can have metadata. For example, a Docker image.
type V1beta1Resource struct {
	// Deprecated, do not use. Use uri instead.  The name of the resource. For example, the name of a Docker image - \"Debian\".
	Name string `json:"name,omitempty"`
	// Required. The unique URI of the resource. For example, `https://gcr.io/project/image@sha256:foo` for a Docker image.
	Uri string `json:"uri,omitempty"`
	// Deprecated, do not use. Use uri instead.  The hash of the resource content. For example, the Docker digest.
	ContentHash *ProvenanceHash `json:"content_hash,omitempty"`
}
