/*
 * proto/v1beta1/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CvsSv3UserInteraction string

// List of CVSSv3UserInteraction
const (
	UNSPECIFIED_CvsSv3UserInteraction CvsSv3UserInteraction = "USER_INTERACTION_UNSPECIFIED"
	NONE_CvsSv3UserInteraction CvsSv3UserInteraction = "USER_INTERACTION_NONE"
	REQUIRED_CvsSv3UserInteraction CvsSv3UserInteraction = "USER_INTERACTION_REQUIRED"
)
