/*
 * proto/v1beta1/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Details of an image occurrence.
type V1beta1imageDetails struct {
	// Required. Immutable. The child image derived from the base image.
	DerivedImage *ImageDerived `json:"derived_image,omitempty"`
}
