/*
 * proto/v1beta1/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type CvsSv3AttackComplexity string

// List of CVSSv3AttackComplexity
const (
	UNSPECIFIED_CvsSv3AttackComplexity CvsSv3AttackComplexity = "ATTACK_COMPLEXITY_UNSPECIFIED"
	LOW_CvsSv3AttackComplexity CvsSv3AttackComplexity = "ATTACK_COMPLEXITY_LOW"
	HIGH_CvsSv3AttackComplexity CvsSv3AttackComplexity = "ATTACK_COMPLEXITY_HIGH"
)
