/*
 * proto/v1beta1/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CvsSv3Impact string

// List of CVSSv3Impact
const (
	UNSPECIFIED_CvsSv3Impact CvsSv3Impact = "IMPACT_UNSPECIFIED"
	HIGH_CvsSv3Impact CvsSv3Impact = "IMPACT_HIGH"
	LOW_CvsSv3Impact CvsSv3Impact = "IMPACT_LOW"
	NONE_CvsSv3Impact CvsSv3Impact = "IMPACT_NONE"
)
