/*
 * proto/v1beta1/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type CvsSv3Scope string

// List of CVSSv3Scope
const (
	UNSPECIFIED_CvsSv3Scope CvsSv3Scope = "SCOPE_UNSPECIFIED"
	UNCHANGED_CvsSv3Scope CvsSv3Scope = "SCOPE_UNCHANGED"
	CHANGED_CvsSv3Scope CvsSv3Scope = "SCOPE_CHANGED"
)
