/*
 * proto/v1beta1/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

import (
	"time"
)

// Provides information about the analysis status of a discovered resource.
type DiscoveryDiscovered struct {
	// Whether the resource is continuously analyzed.
	ContinuousAnalysis *DiscoveredContinuousAnalysis `json:"continuous_analysis,omitempty"`
	// The last time continuous analysis was done for this resource. Deprecated, do not use.
	LastAnalysisTime time.Time `json:"last_analysis_time,omitempty"`
	// The status of discovery for the resource.
	AnalysisStatus *DiscoveredAnalysisStatus `json:"analysis_status,omitempty"`
	// When an error is encountered this will contain a LocalizedMessage under details to show to the user. The LocalizedMessage is output only and populated by the API.
	AnalysisStatusError *RpcStatus `json:"analysis_status_error,omitempty"`
}
