/*
 * project.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Describes a Grafeas project.
type ProjectProject struct {
	// The name of the project in the form of `projects/{PROJECT_ID}`.
	Name string `json:"name,omitempty"`
}
