/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

import (
	"time"
)

// Specifies details on how to handle (and presumably, fix) a vulnerability.
type AssessmentRemediation struct {
	// The type of remediation that can be applied.
	RemediationType *RemediationRemediationType `json:"remediationType,omitempty"`
	// Contains the date from which the remediation is available.
	RemediationTime time.Time `json:"remediationTime,omitempty"`
	// Contains a comprehensive human-readable discussion of the remediation.
	Details string `json:"details,omitempty"`
	// Contains the URL where to obtain the remediation.
	RemediationUri *V1beta1RelatedUrl `json:"remediationUri,omitempty"`
}
