/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Response for creating notes in batch.
type V1beta1BatchCreateNotesResponse struct {
	// The notes that were created.
	Notes []V1beta1Note `json:"notes,omitempty"`
}
