/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type SpdxPackageInfoOccurrence struct {
	Id string `json:"id,omitempty"`
	Filename string `json:"filename,omitempty"`
	SourceInfo string `json:"sourceInfo,omitempty"`
	LicenseConcluded *V1beta1License `json:"licenseConcluded,omitempty"`
	Comment string `json:"comment,omitempty"`
	// The type of package: OS, MAVEN, GO, GO_STDLIB, etc.
	PackageType string `json:"packageType,omitempty"`
	Title string `json:"title,omitempty"`
	Version string `json:"version,omitempty"`
	HomePage string `json:"homePage,omitempty"`
	SummaryDescription string `json:"summaryDescription,omitempty"`
}
