/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type SpdxDocumentNote struct {
	SpdxVersion string `json:"spdxVersion,omitempty"`
	DataLicence string `json:"dataLicence,omitempty"`
}
