/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Request to create occurrences in batch.
type Body1 struct {
	// The occurrences to create. Max allowed length is 1000.
	Occurrences []V1beta1Occurrence `json:"occurrences"`
}
