/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Layer holds metadata specific to a layer of a Docker image.
type ImageLayer struct {
	// Required. The recovered Dockerfile directive used to construct this layer.
	Directive *LayerDirective `json:"directive,omitempty"`
	// The recovered arguments to the Dockerfile directive.
	Arguments string `json:"arguments,omitempty"`
}
