/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type PackageInfoNoteExternalRef struct {
	Category *ExternalRefCategory `json:"category,omitempty"`
	Type_ string `json:"type,omitempty"`
	Locator string `json:"locator,omitempty"`
	Comment string `json:"comment,omitempty"`
}
