/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Details of an attestation occurrence.
type V1beta1attestationDetails struct {
	// Required. Attestation for the resource.
	Attestation *AttestationAttestation `json:"attestation,omitempty"`
}
