/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas
// RemediationRemediationType : The type of remediation that can be applied.   - REMEDIATION_TYPE_UNSPECIFIED: No remediation type specified.  - MITIGATION: A MITIGATION is available.  - NO_FIX_PLANNED: No fix is planned.  - NONE_AVAILABLE: Not available.  - VENDOR_FIX: A vendor fix is available.  - WORKAROUND: A workaround is available.
type RemediationRemediationType string

// List of RemediationRemediationType
const (
	REMEDIATION_TYPE_UNSPECIFIED_RemediationRemediationType RemediationRemediationType = "REMEDIATION_TYPE_UNSPECIFIED"
	MITIGATION_RemediationRemediationType RemediationRemediationType = "MITIGATION"
	NO_FIX_PLANNED_RemediationRemediationType RemediationRemediationType = "NO_FIX_PLANNED"
	NONE_AVAILABLE_RemediationRemediationType RemediationRemediationType = "NONE_AVAILABLE"
	VENDOR_FIX_RemediationRemediationType RemediationRemediationType = "VENDOR_FIX"
	WORKAROUND_RemediationRemediationType RemediationRemediationType = "WORKAROUND"
)
