/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type CvssUserInteraction string

// List of CVSSUserInteraction
const (
	UNSPECIFIED_CvssUserInteraction CvssUserInteraction = "USER_INTERACTION_UNSPECIFIED"
	NONE_CvssUserInteraction CvssUserInteraction = "USER_INTERACTION_NONE"
	REQUIRED_CvssUserInteraction CvssUserInteraction = "USER_INTERACTION_REQUIRED"
)
