/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Digest information.
type V1beta1Digest struct {
	// `SHA1`, `SHA512` etc.
	Algo string `json:"algo,omitempty"`
	// Value of the digest.
	DigestBytes string `json:"digestBytes,omitempty"`
}
