/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Indicates which analysis completed successfully. Multiple types of analysis can be performed on a single resource.
type DiscoveredAnalysisCompleted struct {
	AnalysisType []string `json:"analysisType,omitempty"`
}
