/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Justification provides the justification when the state of the assessment if NOT_AFFECTED.
type AssessmentJustification struct {
	// The justification type for this vulnerability.
	JustificationType *JustificationJustificationType `json:"justificationType,omitempty"`
	// Additional details on why this justification was chosen.
	Details string `json:"details,omitempty"`
}
