/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// VexAssessment provides all publisher provided Vex information that is related to this vulnerability.
type DetailsVexAssessment struct {
	// Holds the MITRE standard Common Vulnerabilities and Exposures (CVE) tracking number for the vulnerability.
	Cve string `json:"cve,omitempty"`
	// Holds a list of references associated with this vulnerability item and assessment.
	RelatedUris []V1beta1RelatedUrl `json:"relatedUris,omitempty"`
	NoteName string `json:"noteName,omitempty"`
	// Provides the state of this Vulnerability assessment.
	State *AssessmentState `json:"state,omitempty"`
	// Contains information about the impact of this vulnerability, this will change with time.
	Impacts []string `json:"impacts,omitempty"`
	// Specifies details on how to handle (and presumably, fix) a vulnerability.
	Remediations []AssessmentRemediation `json:"remediations,omitempty"`
	// Justification provides the justification when the state of the assessment if NOT_AFFECTED.
	Justification *AssessmentJustification `json:"justification,omitempty"`
}
