/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type V1beta1EnvelopeSignature struct {
	Sig string `json:"sig,omitempty"`
	Keyid string `json:"keyid,omitempty"`
}
