/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Details of a package occurrence.
type V1beta1packageDetails struct {
	// Required. Where the package was installed.
	Installation *PackageInstallation `json:"installation,omitempty"`
}
