/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type SpdxRelationshipOccurrence struct {
	Source string `json:"source,omitempty"`
	Target string `json:"target,omitempty"`
	Type_ *SpdxRelationshipType `json:"type,omitempty"`
	Comment string `json:"comment,omitempty"`
}
