/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Package represents a particular package version.
type PackagePackage struct {
	// The name of the package.
	Name string `json:"name"`
	// The various channels by which a package is distributed.
	Distribution []PackageDistribution `json:"distribution,omitempty"`
	// The type of package; whether native or non native (e.g., ruby gems, node.js packages, etc.).
	PackageType string `json:"packageType,omitempty"`
	// The cpe_uri in [CPE format](https://cpe.mitre.org/specification/) denoting the package manager version distributing a package. The cpe_uri will be blank for language packages.
	CpeUri string `json:"cpeUri,omitempty"`
	// The CPU architecture for which packages in this distribution channel were built. Architecture will be blank for language packages.
	Architecture *PackageArchitecture `json:"architecture,omitempty"`
	// The version of the package.
	Version *PackageVersion `json:"version,omitempty"`
	// A freeform text denoting the maintainer of this package.
	Maintainer string `json:"maintainer,omitempty"`
	// The homepage for this package.
	Url string `json:"url,omitempty"`
	// The description of this package.
	Description string `json:"description,omitempty"`
	// Licenses that have been declared by the authors of the package.
	License *V1beta1License `json:"license,omitempty"`
	// Hash value, typically a file digest, that allows unique identification a specific package.
	Digest []V1beta1Digest `json:"digest,omitempty"`
}
