/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// MUST match https://github.com/secure-systems-lab/dsse/blob/master/envelope.proto. An authenticated message of arbitrary type.
type V1beta1Envelope struct {
	Payload string `json:"payload,omitempty"`
	PayloadType string `json:"payloadType,omitempty"`
	Signatures []V1beta1EnvelopeSignature `json:"signatures,omitempty"`
}
