/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Version contains structured information about the version of a package.
type PackageVersion struct {
	// Used to correct mistakes in the version numbering scheme.
	Epoch int32 `json:"epoch,omitempty"`
	// Required only when version kind is NORMAL. The main part of the version name.
	Name string `json:"name,omitempty"`
	// The iteration of the package build from the above version.
	Revision string `json:"revision,omitempty"`
	// Whether this version is specifying part of an inclusive range. Grafeas does not have the capability to specify version ranges; instead we have fields that specify start version and end versions. At times this is insufficient - we also need to specify whether the version is included in the range or is excluded from the range. This boolean is expected to be set to true when the version is included in a range.
	Inclusive bool `json:"inclusive,omitempty"`
	// Required. Distinguishes between sentinel MIN/MAX versions and normal versions.
	Kind *VersionVersionKind `json:"kind,omitempty"`
}
