/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas
// ExternalRefCategory : - CATEGORY_UNSPECIFIED: Unspecified  - SECURITY: Security (e.g. cpe22Type, cpe23Type)  - PACKAGE_MANAGER: Package Manager (e.g. maven-central, npm, nuget, bower, purl)  - PERSISTENT_ID: Persistent-Id (e.g. swh)  - OTHER: Other
type ExternalRefCategory string

// List of ExternalRefCategory
const (
	CATEGORY_UNSPECIFIED_ExternalRefCategory ExternalRefCategory = "CATEGORY_UNSPECIFIED"
	SECURITY_ExternalRefCategory ExternalRefCategory = "SECURITY"
	PACKAGE_MANAGER_ExternalRefCategory ExternalRefCategory = "PACKAGE_MANAGER"
	PERSISTENT_ID_ExternalRefCategory ExternalRefCategory = "PERSISTENT_ID"
	OTHER_ExternalRefCategory ExternalRefCategory = "OTHER"
)
