/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// A SourceContext referring to a Gerrit project.
type SourceGerritSourceContext struct {
	// The URI of a running Gerrit instance.
	HostUri string `json:"hostUri,omitempty"`
	// The full project name within the host. Projects may be nested, so \"project/subproject\" is a valid project name. The \"repo name\" is the hostURI/project.
	GerritProject string `json:"gerritProject,omitempty"`
	// A revision (commit) ID.
	RevisionId string `json:"revisionId,omitempty"`
	// An alias, which may be a branch or tag.
	AliasContext *SourceAliasContext `json:"aliasContext,omitempty"`
}
