/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type SpdxFileNote struct {
	Title string `json:"title,omitempty"`
	FileType *FileNoteFileType `json:"fileType,omitempty"`
	Checksum []string `json:"checksum,omitempty"`
}
