/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Details of a deployment occurrence.
type V1beta1deploymentDetails struct {
	// Required. Deployment history for the resource.
	Deployment *DeploymentDeployment `json:"deployment,omitempty"`
}
