/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type SpdxPackageInfoNote struct {
	Title string `json:"title,omitempty"`
	Version string `json:"version,omitempty"`
	Supplier string `json:"supplier,omitempty"`
	Originator string `json:"originator,omitempty"`
	DownloadLocation string `json:"downloadLocation,omitempty"`
	Analyzed bool `json:"analyzed,omitempty"`
	VerificationCode string `json:"verificationCode,omitempty"`
	Checksum string `json:"checksum,omitempty"`
	HomePage string `json:"homePage,omitempty"`
	FilesLicenseInfo []string `json:"filesLicenseInfo,omitempty"`
	LicenseDeclared *V1beta1License `json:"licenseDeclared,omitempty"`
	Copyright string `json:"copyright,omitempty"`
	SummaryDescription string `json:"summaryDescription,omitempty"`
	DetailedDescription string `json:"detailedDescription,omitempty"`
	ExternalRefs []PackageInfoNoteExternalRef `json:"externalRefs,omitempty"`
	Attribution string `json:"attribution,omitempty"`
	// The type of package: OS, MAVEN, GO, GO_STDLIB, etc.
	PackageType string `json:"packageType,omitempty"`
}
