/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

import (
	"time"
)

type SpdxDocumentOccurrence struct {
	Id string `json:"id,omitempty"`
	Title string `json:"title,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	ExternalDocumentRefs []string `json:"externalDocumentRefs,omitempty"`
	LicenseListVersion string `json:"licenseListVersion,omitempty"`
	Creators []string `json:"creators,omitempty"`
	CreateTime time.Time `json:"createTime,omitempty"`
	CreatorComment string `json:"creatorComment,omitempty"`
	DocumentComment string `json:"documentComment,omitempty"`
}
