/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas
// AssessmentState : Provides the state of this Vulnerability assessment.   - STATE_UNSPECIFIED: No state is specified.  - AFFECTED: This product is known to be affected by this vulnerability.  - NOT_AFFECTED: This product is known to be not affected by this vulnerability.  - FIXED: This product contains a fix for this vulnerability.  - UNDER_INVESTIGATION: It is not known yet whether these versions are or are not affected by the vulnerability. However, it is still under investigation.
type AssessmentState string

// List of AssessmentState
const (
	STATE_UNSPECIFIED_AssessmentState AssessmentState = "STATE_UNSPECIFIED"
	AFFECTED_AssessmentState AssessmentState = "AFFECTED"
	NOT_AFFECTED_AssessmentState AssessmentState = "NOT_AFFECTED"
	FIXED_AssessmentState AssessmentState = "FIXED"
	UNDER_INVESTIGATION_AssessmentState AssessmentState = "UNDER_INVESTIGATION"
)
