/*
 * grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// This represents how a particular software package may be installed on a system.
type PackageInstallation struct {
	// The name of the installed package.
	Name string `json:"name"`
	// All of the places within the filesystem versions of this package have been found.
	Location []V1beta1packageLocation `json:"location,omitempty"`
	// The type of package; whether native or non native (e.g., ruby gems, node.js packages, etc.).
	PackageType string `json:"packageType,omitempty"`
	// The cpe_uri in [CPE format](https://cpe.mitre.org/specification/) denoting the package manager version distributing a package. The cpe_uri will be blank for language packages.
	CpeUri string `json:"cpeUri,omitempty"`
	// The CPU architecture for which packages in this distribution channel were built. Architecture will be blank for language packages.
	Architecture *PackageArchitecture `json:"architecture,omitempty"`
	// Licenses that have been declared by the authors of the package.
	License *V1beta1License `json:"license,omitempty"`
	// The version of the package.
	Version *PackageVersion `json:"version,omitempty"`
}
