/*
 * v1alpha1/proto/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Container message for hashes of byte content of files, used in Source messages to verify integrity of source input to the build.
type ApiFileHashes struct {

	// Collection of file hashes.
	FileHash []ApiHash `json:"file_hash,omitempty"`
}
