/*
 * v1alpha1/proto/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// An alias to a repo revision.
type ApiAliasContext struct {

	// The alias kind.
	Kind *ApiAliasContextKind `json:"kind,omitempty"`

	// The alias name.
	Name string `json:"name,omitempty"`
}
