/*
 * v1alpha1/proto/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Note holding the version of the provider's builder and the signature of the provenance message in linked BuildDetails.
type ApiBuildType struct {

	// Version of the builder which produced this Note.
	BuilderVersion string `json:"builder_version,omitempty"`

	// Signature of the build in Occurrences pointing to the Note containing this `BuilderDetails`.
	Signature *ApiBuildSignature `json:"signature,omitempty"`
}
