/*
 * v1alpha1/proto/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Container message for hash values.
type ApiHash struct {

	// The type of hash that was performed.
	Type_ *HashHashType `json:"type,omitempty"`

	// The hash value.
	Value string `json:"value,omitempty"`
}
