/*
 * v1alpha1/proto/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Response including listed notes.
type ApiListNotesResponse struct {

	Notes []ApiNote `json:"notes,omitempty"`

	// The next pagination token in the list response. It should be used as page_token for the following request. An empty value means no more result.
	NextPageToken string `json:"next_page_token,omitempty"`
}
