/*
 * v1alpha1/proto/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type ApiUpdateOperationRequest struct {

	// The name of the Operation. Should be of the form \"projects/{provider_id}/operations/{operation_id}\".
	Name string `json:"name,omitempty"`

	// The operation to create.
	Operation *LongrunningOperation `json:"operation,omitempty"`
}
