/*
 * v1alpha1/proto/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type AttestationAuthorityAttestationAuthorityHint struct {

	// The human readable name of this Attestation Authority, e.g. \"qa\".
	HumanReadableName string `json:"human_readable_name,omitempty"`
}
