/*
 * v1alpha1/proto/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas
// DeploymentDetailsPlatform : Types of platforms.   - PLATFORM_UNSPECIFIED: Unknown  - GKE: Google Container Engine  - FLEX: Google App Engine: Flexible Environment  - CUSTOM: Custom user-defined platform
type DeploymentDetailsPlatform string

// List of DeploymentDetailsPlatform
const (
	PLATFORM_UNSPECIFIED DeploymentDetailsPlatform = "PLATFORM_UNSPECIFIED"
	GKE DeploymentDetailsPlatform = "GKE"
	FLEX DeploymentDetailsPlatform = "FLEX"
	CUSTOM DeploymentDetailsPlatform = "CUSTOM"
)
