/*
 * v1alpha1/proto/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Provides information about the scan status of a discovered resource.
type DiscoveryDiscoveredDetails struct {

	// Output only. An operation that indicates the status of the current scan.
	Operation *LongrunningOperation `json:"operation,omitempty"`
}
