/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Container message for hash values.
type ApiHash struct {
	// The type of hash that was performed.
	Type_ *HashHashType `json:"type,omitempty"`
	// The hash value.
	Value string `json:"value,omitempty"`
}
