/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

type ApiUpdateOperationRequest struct {
	// The name of the Operation. Should be of the form \"projects/{provider_id}/operations/{operation_id}\".
	Name string `json:"name,omitempty"`
	// The operation to create.
	Operation *LongrunningOperation `json:"operation,omitempty"`
}
