/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// An alias to a repo revision.
type ApiAliasContext struct {
	// The alias kind.
	Kind *ApiAliasContextKind `json:"kind,omitempty"`
	// The alias name.
	Name string `json:"name,omitempty"`
}
