/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas
// DeploymentDetailsPlatform : Types of platforms.   - PLATFORM_UNSPECIFIED: Unknown  - GKE: Google Container Engine  - FLEX: Google App Engine: Flexible Environment  - CUSTOM: Custom user-defined platform
type DeploymentDetailsPlatform string

// List of DeploymentDetailsPlatform
const (
	PLATFORM_UNSPECIFIED DeploymentDetailsPlatform = "PLATFORM_UNSPECIFIED"
	GKE DeploymentDetailsPlatform = "GKE"
	FLEX DeploymentDetailsPlatform = "FLEX"
	CUSTOM DeploymentDetailsPlatform = "CUSTOM"
)
