/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NoteRelatedUrl struct {
	Url string `json:"url,omitempty"`

	Label string `json:"label,omitempty"`
}
