/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Response including listed occurrences for a note.
type ApiListNoteOccurrencesResponse struct {
	// The occurrences attached to the specified note.
	Occurrences []ApiOccurrence `json:"occurrences,omitempty"`
	// Token to receive the next page of notes.
	NextPageToken string `json:"next_page_token,omitempty"`
}
