/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

import (
	"time"
)

// Provenance of a build. Contains all information needed to verify the full details about the build from source to completion.
type ApiBuildProvenance struct {
	// Unique identifier of the build.
	Id string `json:"id,omitempty"`
	// ID of the project.
	ProjectId string `json:"project_id,omitempty"`
	// Commands requested by the build.
	Commands []ApiCommand `json:"commands,omitempty"`
	// Output of the build.
	BuiltArtifacts []ApiArtifact `json:"built_artifacts,omitempty"`
	// Time at which the build was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// Time at which execution of the build was started.
	StartTime time.Time `json:"start_time,omitempty"`
	// Time at which execution of the build was finished.
	FinishTime time.Time `json:"finish_time,omitempty"`
	// E-mail address of the user who initiated this build. Note that this was the user's e-mail address at the time the build was initiated; this address may not represent the same end-user for all time.
	Creator string `json:"creator,omitempty"`
	// Google Cloud Storage bucket where logs were written.
	LogsBucket string `json:"logs_bucket,omitempty"`
	// Details of the Source input to the build.
	SourceProvenance *ApiSource `json:"source_provenance,omitempty"`
	// Trigger identifier if the build was triggered automatically; empty if not.
	TriggerId string `json:"trigger_id,omitempty"`
	// Special options applied to this build. This is a catch-all field where build providers can enter any desired additional details.
	BuildOptions map[string]string `json:"build_options,omitempty"`
	// Version string of the builder at the time this build was executed.
	BuilderVersion string `json:"builder_version,omitempty"`
}
