/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Response including listed notes.
type ApiListNotesResponse struct {
	Notes []ApiNote `json:"notes,omitempty"`
	// The next pagination token in the list response. It should be used as page_token for the following request. An empty value means no more result.
	NextPageToken string `json:"next_page_token,omitempty"`
}
