/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// Derived describes the derived image portion (Occurrence) of the DockerImage relationship.  This image would be produced from a Dockerfile with FROM <DockerImage.Basis in attached Note>.
type DockerImageDerivedDetails struct {
	Fingerprint *DockerImageFingerprint `json:"fingerprint,omitempty"`
	// Output only. The number of layers by which this image differs from the associated image basis.
	Distance int64 `json:"distance,omitempty"`
	// This contains layer-specific metadata, if populated it has length \"distance\" and is ordered with [distance] being the layer immediately following the base image and [1] being the final layer.
	LayerInfo []DockerImageLayer `json:"layer_info,omitempty"`
	BaseResourceUrl string `json:"base_resource_url,omitempty"`
}
