/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// RepoSource describes the location of the source in a Google Cloud Source Repository.
type ApiRepoSource struct {
	// ID of the project that owns the repo.
	ProjectId string `json:"project_id,omitempty"`
	// Name of the repo.
	RepoName string `json:"repo_name,omitempty"`
	// Name of the branch to build.
	BranchName string `json:"branch_name,omitempty"`
	// Name of the tag to build.
	TagName string `json:"tag_name,omitempty"`
	// Explicit commit SHA to build.
	CommitSha string `json:"commit_sha,omitempty"`
}
