/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas

// A unique identifier for a Cloud Repo.
type ApiRepoId struct {
	// A combination of a project ID and a repo name.
	ProjectRepoId *ApiProjectRepoId `json:"project_repo_id,omitempty"`
	// A server-assigned, globally unique identifier.
	Uid string `json:"uid,omitempty"`
}
