/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas
// HashHashType : Specifies the hash algorithm, if any.   - NONE: No hash requested.  - SHA256: A sha256 hash.
type HashHashType string

// List of HashHashType
const (
	NONE HashHashType = "NONE"
	SHA256 HashHashType = "SHA256"
)
