/*
 * v1alpha1/proto/grafeas.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package grafeas
// VersionVersionKind : Whether this is an ordinary package version or a sentinel MIN/MAX version.   - NORMAL: A standard package version, defined by the other fields.  - MINIMUM: A special version representing negative infinity, other fields are ignored.  - MAXIMUM: A special version representing positive infinity, other fields are ignored.
type VersionVersionKind string

// List of VersionVersionKind
const (
	NORMAL VersionVersionKind = "NORMAL"
	MINIMUM VersionVersionKind = "MINIMUM"
	MAXIMUM VersionVersionKind = "MAXIMUM"
)
